sequenceDiagram
    autonumber
    actor patient as Patient
    participant nhsApp as NHS App
    participant taskingSolution as Tasking Solution
    participant nds as National Diagnostic Service (NDS)
    participant nhsAppointmentBookingService as NHS Appointment Booking Service


    patient ->>+ nhsApp : Access application to view tasks
    nhsApp ->>+ taskingSolution : Request list of patient tasks
    taskingSolution -->>- nhsApp : List of tasks
    nhsApp -->>- patient : Display list of tasks to patient
    patient ->>+ nhsApp: Patient selects book diagnostic test task
    nhsApp ->>+ nds: Request relevent Diagnostic Test details 
    nds -->>- nhsApp: Return Diagnostic Test Details
    nhsApp ->>- patient: Display Diagnostic Test Details to patient
    patient ->> nhsApp: Patient confirms to book diagnostic test
    nhsApp ->> nhsAppointmentBookingService: Route patient to appointment booking service
    