sequenceDiagram
    autonumber
    participant orderingClinician as Ordering Clinician
    participant patient as Patient
    participant nhsApp as NHS App
    participant taskingSolution as Tasking Solution
    participant nhsAppointmentBookingService as NHS Appointment Booking Service
    participant serviceSelection as Service Selection
    participant nds as National Diagnostic Service (NDS)
    participant ndsDos as NDS Directory of Services (NDS Dos)
    participant journeyTracking as Journery Tracking Solution
    participant pds as Personal Demographics Service (PDS)
    participant mns as Message Notification Service (MNS)
    participant barsProxy as BARS Proxy
    participant appointmentProvider as Care Setting Appointment Solution
    participant LIMS as Laboratory Information Management System (LIMS) / Radiology Information System (RIS) 
    participant providerClinican as Provider Clinician
    participant nhsNotify as NHS Notify

    orderingClinician ->> nds : Orders diagnostic test for patient
    par NDS creates patient task for booking diagnostic test
        nds ->> taskingSolution : Create patient task for booking diagnostic test
        taskingSolution -->> nds : Confrim task creation
        nds ->> nhsNotify : Notify patient of booking task
        nhsNotify -) patient : Notify patient of booking task  
    and NDS notifies Journey Tracking Solution of new diagnostic test order
        nds ->> journeyTracking : Notify of new diagnostic test order
        journeyTracking -->> nds : Confirm notification received
    end
    patient ->> nhsApp : Access Application
    nhsApp ->> taskingSolution : Request list of patient tasks
    taskingSolution -->> nhsApp : List of tasks
    nhsApp -->> patient : Display list of tasks to patient
    patient ->> nhsApp: Patient selects book diagnostic test task
    nhsApp ->> nds: Request relevent Diagnostic Test details 
    nds -->> nhsApp: Return Diagnostic Test Details
    nhsApp ->> patient: Display Diagnostic Test Details to patient
    patient ->> nhsApp: Patient confirms to book diagnostic test
    nhsApp ->> nhsAppointmentBookingService: Route patient to appointment booking service
    nhsAppointmentBookingService ->> serviceSelection: Request diagnostic test provider list with search criteria (e.g. location)
    serviceSelection ->> nds: Request diagnostic test provider list with search criteria (e.g. location)
    nds ->> pds: Request patient demographics
    pds -->> nds: Return patient demographics
    nds ->> ndsDos: Request provider list including search criteria and patient demographics
    ndsDos -->> nds: Return provider list
    nds -->> serviceSelection: Return provider list
    serviceSelection -->> nhsAppointmentBookingService: Return provider list
    alt Dianostic Test has Simple Vetting
        loop Every Provider
            nhsAppointmentBookingService ->> barsProxy: Request available appointments for provider
            barsProxy ->> appointmentProvider: Request available appointments for provider
            appointmentProvider -->> barsProxy: Return available appointments for provider
            barsProxy -->> nhsAppointmentBookingService: Return available appointments for provider
        end
        nhsAppointmentBookingService -->> nhsApp: Return available providers and available appointments
        nhsApp -->> patient: Display available providers and appointments to patient    
        patient ->> nhsAppointmentBookingService: Patient selects appointment at their chosen provider
        nhsAppointmentBookingService ->> barsProxy: Book appointment with provider
        barsProxy ->> appointmentProvider: Book appointment with provider
        appointmentProvider -->> barsProxy: Return appointment booked confirmation
        barsProxy -->> nhsAppointmentBookingService: Return appointment booked confirmation
        nhsAppointmentBookingService ->> mns: New patient appointment event
        mns ->> nds: Notify diagnostic service of new patient appointment
        nhsAppointmentBookingService -->> nhsApp: Return appointment booked confirmation 
        nhsApp -->> patient: Display appointment booked confirmation to patient       
        nds ->> LIMS : Send diagnostic test order to provider
    else Diagnostic Test has Provider Specific ComplexVetting
        nhsAppointmentBookingService -->> nhsApp: Return available providers
        nhsApp -->> patient: Display available providers and appointments to patient
        patient ->> nhsAppointmentBookingService: Patient selects provider
        nhsAppointmentBookingService -> mns: Notify diagnostic service of patient provider selection
        mns ->> nds: Notify diagnostic service of patient provider selection
        mns ->> LIMS : Notify provider of patient provider selection
        LIMS ->> nds : Request diagnostic test order
        nds -->> LIMS : Return diagnostic test order to provider
        LIMS -) providerClinican : Vetting of patient and test order
        providerClinican --> LIMS : Return vetting outcome
        providerClinican ->> appointmentProvider : Unlock appointment booking for patient
        appointmentProvider ->> mns: Notify outcome of vetting and acceptance of patient
        mns ->> nds: Notify diagnostic service of patient vetting outcome and acceptance of patient
        nds ->> taskingSolution : Create Patient task for appointment booking
        taskingSolution ->> nhsNotify : Notify patient of appointment booking task
        nhsNotify -) Patient : Notify patient of appointment booking task
        patient ->> nhsApp : Access Application
        nhsApp ->> taskingSolution : Request list of patient tasks
        taskingSolution -->> nhsApp : Return list of patient tasks
        nhsApp ->> patient : Display list of patient tasks
        patient ->> nhsApp: Patient selects appointment booking Task
        nhsApp ->> nhsAppointmentBookingService: Route patient to appointment booking service
        nhsAppointmentBookingService ->> barsProxy: Request available appointments for provider
        barsProxy ->> appointmentProvider: Request available appointments for provider
        appointmentProvider -->> barsProxy: Return available appointments for provider
        barsProxy -->>  nhsAppointmentBookingService: Return available appointments for provider
        nhsAppointmentBookingService -->> nhsApp: Return available appointments for provider
        nhsApp -->> patient: Display available appointments to patient  
        patient --> nhsAppointmentBookingService: Patient selects appointment
        nhsAppointmentBookingService ->> barsProxy: Book appointment with provider
        barsProxy ->> appointmentProvider: Book appointment with provider
        appointmentProvider -->> barsProxy: Return appointment booked confirmation
        barsProxy -->> nhsAppointmentBookingService: Return appointment booked confirmation
        nhsAppointmentBookingService ->> mns: New patient appointment event
        mns ->> nds: Notify diagnostic service of new patient appointment
        nhsAppointmentBookingService -->> nhsApp: Return appointment booked confirmation 
        nhsApp -->> patient: Display appointment booked confirmation to patient      
    else Diagnostic Test has Provider Complex Vetting and Appointment assignment
        nhsAppointmentBookingService -->> nhsApp: Return available providers
        nhsApp -->> patient: Display available providers and appointments to patient
        patient ->> nhsAppointmentBookingService: Patient selects provider
        nhsAppointmentBookingService -> mns: Notify diagnostic service of patient provider selection
        mns ->> nds: Notify diagnostic service of patient provider selection
        mns ->> LIMS : Notify provider of patient provider selection
        LIMS ->> nds : Request diagnostic test order
        nds -->> LIMS : Return diagnostic test order details
        LIMS -) providerClinican : Vetting of patient and test order
        providerClinican --) LIMS : Return vetting outcome
        providerClinican -) appointmentProvider : Assign Appointment to patient
        appointmentProvider ->> mns: New patient appointment event
        mns ->> nds: Notify diagnostic service of new patient appointment
        mns -->> nhsAppointmentBookingService: Return appointment booked confirmation 
        nhsAppointmentBookingService -->> nhsNotify: Notify patient of appointment assignment
        nhsNotify -) patient: Notify patient of appointment assignment


    end
    